[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = [
    "-C",
    "target-feature=+atomics,+bulk-memory",
    "--cfg",
    'getrandom_backend="wasm_js"',
]

[unstable]
build-std = ["panic_abort", "std"]
