[package]
name = "vis-rs"
version = "1.0.0-dev.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
rand = "0.9"
rayon = "1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-bindgen-rayon = "1"
wee_alloc = { version = "0.4", optional = true }

[dependencies.bevy]
version = "0.16"
default-features = false
features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "bevy_winit",
    "bevy_state",
    "webgl2",
]

[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1"
